import { initializeApp, getApps } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import { getDatabase, ref, push, set, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-database.js";
import { firebaseConfig } from "./firebase-config.js";
const app=getApps().length?getApps()[0]:initializeApp(firebaseConfig),db=getDatabase(app);
function deviceInfo(){const ua=navigator.userAgent;let device="Other";if(/iPhone|iPad|iPod/i.test(ua))device="iOS";else if(/Android/i.test(ua))device="Android";else if(/Windows/i.test(ua))device="Windows";else if(/Macintosh|Mac OS X/i.test(ua))device="Mac";let browser="Other";if(/CriOS|Chrome/i.test(ua)&&!/Edg/i.test(ua))browser="Chrome";else if(/Safari/i.test(ua)&&!/Chrome|CriOS/i.test(ua))browser="Safari";else if(/Firefox/i.test(ua))browser="Firefox";else if(/Edg/i.test(ua))browser="Edge";return{device,browser}}
async function approximateLocation(){const cached=sessionStorage.getItem("apdcApproxLocation");if(cached){try{return JSON.parse(cached)}catch{}}try{const c=new AbortController(),t=setTimeout(()=>c.abort(),3500),r=await fetch("https://ipwho.is/",{signal:c.signal,cache:"no-store"});clearTimeout(t);const d=await r.json(),x=d.success===false?{}:{country:d.country||"Unknown",countryCode:d.country_code||"",city:d.city||"Unknown",region:d.region||""};sessionStorage.setItem("apdcApproxLocation",JSON.stringify(x));return x}catch{return{country:"Unknown",countryCode:"",city:"Unknown",region:""}}}
function dayKey(){const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function sessionId(){let id=sessionStorage.getItem("apdcAnalyticsSession");if(!id){id=crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`;sessionStorage.setItem("apdcAnalyticsSession",id)}return id}
async function basePayload(){const loc=await approximateLocation(),device=deviceInfo();return{...loc,...device,language:localStorage.getItem("apdcLang")||navigator.language||"en",timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||"",referrer:document.referrer?new URL(document.referrer).hostname:"direct",sessionId:sessionId(),day:dayKey(),timestamp:serverTimestamp()}}
async function recordVisit(){if(sessionStorage.getItem("apdcVisitRecorded")==="yes")return;sessionStorage.setItem("apdcVisitRecorded","yes");const p=await basePayload();await push(ref(db,"searchAnalytics/visits"),p);await set(ref(db,`searchAnalytics/presence/${sessionId()}`),{...p,lastSeen:Date.now()})}
async function heartbeat(){const p=await basePayload();await set(ref(db,`searchAnalytics/presence/${sessionId()}`),{...p,lastSeen:Date.now()})}
window.apdcTrackSearch=async(term,resultCount)=>{const clean=String(term||"").trim().slice(0,100);if(!clean)return;const p=await basePayload();await push(ref(db,"searchAnalytics/searches"),{...p,term:clean,resultCount:Number(resultCount)||0,success:Number(resultCount)>0})};
window.apdcTrackSection=async section=>{const p=await basePayload();await push(ref(db,"searchAnalytics/sectionClicks"),{...p,section:String(section||"").slice(0,80)})};
window.apdcTrackPlayer=async(backNo,name)=>{const p=await basePayload();await push(ref(db,"searchAnalytics/playerViews"),{...p,backNo:String(backNo||""),name:String(name||"").slice(0,100)})};
recordVisit();heartbeat();setInterval(heartbeat,60000);document.addEventListener("visibilitychange",()=>{if(!document.hidden)heartbeat()});
