import { initializeApp, getApps } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import { getDatabase, ref, get, remove } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-database.js";
import { firebaseConfig } from "./firebase-config.js";
const app=getApps().length?getApps()[0]:initializeApp(firebaseConfig),db=getDatabase(app),PASSWORD="0070fill";let exportRows=[];
const login=document.getElementById("analyticsLogin"),dashboard=document.getElementById("analyticsDashboard"),pass=document.getElementById("analyticsPassword"),msg=document.getElementById("analyticsLoginMessage");
function unlock(){sessionStorage.setItem("apdcSearchAdmin","yes");login.classList.add("hidden");dashboard.classList.remove("hidden");loadAnalytics()}
document.getElementById("analyticsLoginBtn").onclick=()=>{if(pass.value===PASSWORD)unlock();else msg.textContent="WRONG PASSWORD"};pass.onkeydown=e=>{if(e.key==="Enter")document.getElementById("analyticsLoginBtn").click()};if(sessionStorage.getItem("apdcSearchAdmin")==="yes")unlock();
function todayKey(){const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function countBy(items,keyFn){const m=new Map();items.forEach(x=>{const k=keyFn(x)||"Unknown";m.set(k,(m.get(k)||0)+1)});return[...m.entries()].sort((a,b)=>b[1]-a[1])}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function renderBars(id,data,limit=12){const el=document.getElementById(id),rows=data.slice(0,limit),max=rows[0]?.[1]||1;el.innerHTML=rows.length?rows.map(([l,c])=>`<div class="analytics-row"><span>${esc(l)}</span><div class="analytics-bar"><i style="width:${Math.max(3,c/max*100)}%"></i></div><strong>${c}</strong></div>`).join(""):'<div class="empty">NO DATA</div>'}
function flag(code){if(!code||code.length!==2)return"";return String.fromCodePoint(...code.toUpperCase().split("").map(c=>127397+c.charCodeAt()))}
async function loadAnalytics(){const s=await get(ref(db,"searchAnalytics")),d=s.val()||{},visits=Object.values(d.visits||{}),searches=Object.values(d.searches||{}),players=Object.values(d.playerViews||{}),sections=Object.values(d.sectionClicks||{}),presence=Object.values(d.presence||{}),today=todayKey(),tv=visits.filter(x=>x.day===today),ts=searches.filter(x=>x.day===today);document.getElementById("todayVisitors").textContent=new Set(tv.map(x=>x.sessionId)).size;document.getElementById("todaySearches").textContent=ts.length;document.getElementById("onlineNow").textContent=presence.filter(x=>(x.lastSeen||0)>Date.now()-130000).length;document.getElementById("noResultCount").textContent=ts.filter(x=>!x.success).length;renderBars("countryStats",countBy(tv,x=>`${x.countryCode?flag(x.countryCode)+" ":""}${x.country||"Unknown"}`));renderBars("cityStats",countBy(tv,x=>x.city||"Unknown"));renderBars("topSearches",countBy(searches,x=>x.term));renderBars("topPlayers",countBy(players,x=>`${x.backNo||""} ${x.name||""}`.trim()));renderBars("sectionStats",countBy(sections,x=>x.section));renderBars("deviceStats",countBy(tv,x=>`${x.device||"Unknown"} / ${x.browser||"Unknown"}`));renderBars("languageStats",countBy(tv,x=>x.language||"Unknown"));renderBars("referrerStats",countBy(tv,x=>x.referrer||"direct"));const recent=[...searches].sort((a,b)=>(b.timestamp||0)-(a.timestamp||0)).slice(0,50);document.getElementById("recentSearches").innerHTML=recent.map(x=>`<div class="log-row"><span>${esc(x.term)}</span><small>${esc(x.city||"Unknown")}, ${esc(x.country||"Unknown")} · ${x.resultCount||0} results</small></div>`).join("")||'<div class="empty">NO DATA</div>';renderBars("failedSearches",countBy(searches.filter(x=>!x.success),x=>x.term),30);exportRows=[["type","term_or_name","result_count","country","city","language","device","browser","day"],...searches.map(x=>["search",x.term,x.resultCount,x.country,x.city,x.language,x.device,x.browser,x.day]),...players.map(x=>["player_view",`${x.backNo} ${x.name}`,"",x.country,x.city,x.language,x.device,x.browser,x.day])]}
document.getElementById("refreshAnalytics").onclick=loadAnalytics;document.getElementById("exportAnalytics").onclick=()=>{const csv=exportRows.map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n"),b=new Blob([csv],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=`apdc-search-analytics-${todayKey()}.csv`;a.click();URL.revokeObjectURL(a.href)};document.getElementById("clearAnalytics").onclick=async()=>{if(confirm("Clear all analytics data?")&&confirm("This cannot be undone. Continue?")){await remove(ref(db,"searchAnalytics"));loadAnalytics()}};
